# Name of your application. Used to uniquely configure containers.
service: firebasejwt

# Name of the container image.
image: muthuishere/myregistryproject/firebasejwt

# Deploy to these servers.
servers:
  web:
    - <%= ENV["WEB_SERVER_IP"] %>
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
# If using something like Cloudflare, it is recommended to set encryption mode
# in Cloudflare's SSL/TLS setting to "Full" to enable end-to-end encryption.
proxy:
  ssl: false
  host: firebasejwt.muthuishere.site
  # kamal-proxy connects to your container over port 80, use `app_port` to specify a different port.
  # app_port: 3000

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: <%= ENV["REGISTRY_SERVER"] %>
  username: <%= ENV["REGISTRY_USERNAME"] %>

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password: <%= ENV["GITLAB_REGISTRY_ACCESS_TOKEN"] %>

# Configure builder setup.
builder:
  arch: amd64

